# Mini project 20

Nội dung: Có $N$ bài báo $1, 2,…, N$ khoa học cần được phân cho $M$ nhà khoa học $1, 2, …, M$ để nhận xét phản biện. Tùy thuộc vào lĩnh vực chuyên môn của bài báo và của nhà khoa học mà mỗi bài báo $i$ sẽ tương ứng với $1$ danh sách $L(i)$ các nhà khoa học có thể tham gia phản biện. Mỗi bài báo cần được phân công cho ít nhất $K$ nhà khoa học phản biện để đảm bảo tính tin cậy. Hãy xây dựng phương án phân công phản biện sao cho số lượng bài báo nhiều nhất phân cho một nhà khoa học nào đó phải ít nhất.


## Group 6

1. Nguyễn Duy Hưng
2. Hoàng Thiện Tâm
3. Trần Quốc Lập


## Input

Example:

```
10 7 3
5 1 2 4 6 7
6 1 3 7 2 4 5
4 2 6 7 1
5 4 5 2 1 7
5 3 6 7 1 2
5 4 1 5 3 6
3 1 2 6
4 2 4 7 5
4 5 3 1 4
5 5 4 2 1 3
```

>* Dòng thứ nhất: Nhập vào thứ tự $3$ số $N, M, K$ tương ứng với số bài báo, số nhà khoa học, số nhà khoa học ít nhất cần được phân công cho $1$ bài báo.
>* $N$ dòng tiếp theo, mỗi dòng nhập $q_i + 1$ số ngăn cách bởi dấu cách, số đầu tiên ghi số nhà khoa học có thể phản biện bài báo $i$, $q_i$ sô tiếp theo ghi danh sách các nhà khoa học đó.

## Output

Example:

```
5
1 2 4 
1 2 3 
1 2 6 
1 2 4 
3 6 7 
3 5 6 
1 2 6 
4 5 7 
3 4 5 
3 4 5
```

* the first line: minimized number of articles that can be assigned to the scientist who take the largest workload.
* Next $N$ lines, each line has a sequence of $p_i$ number separated by space that represents the optimal way of assigning.

## Phân tích bài toán

1. **Kí hiệu**:
>* $N$: với số bài báo.
>* $M$: số nhà khoa học.
>* $K$: số nhà khoa học ít nhất được phân công cho $1$ bài báo.
>* $A$: mảng mà ở đó $A_i$ liệt kê danh sách các nhà khoa học có thể đảm nhận bài báo $i$. Ví dụ
>> ```
[[1, 2, 4, 6, 7], 
[1, 2, 3, 4, 5, 7], 
[1, 2, 6, 7], 
[1, 2, 4, 5, 7], 
[1, 2, 3, 6, 7], 
[1, 3, 4, 5, 6], 
[1, 2, 6], 
[2, 4, 5, 7], 
[1, 3, 4, 5], 
[1, 2, 3, 4, 5]]
```
>* $L$: ma trận kích thước $N \times M$, trong đó $L_{ij} = 1$ nếu nhà khoa học $j$ có thể đảm nhận bài báo $i$, hoặc $L_{ij} = 0$ nếu không đảm nhận được. Ví dụ:
>> ```
[[1 1 0 1 0 1 1]
[1 1 1 1 1 0 1]
[1 1 0 0 0 1 1]
[1 1 0 1 1 0 1]
[1 1 1 0 0 1 1]
[1 0 1 1 1 1 0]
[1 1 0 0 0 1 0]
[0 1 0 1 1 0 1]
[1 0 1 1 1 0 0]
[1 1 1 1 1 0 0]]
```
>* $Objective\text{_}value$: số lượng bài báo ít nhất có thể  được phân cho nhà khoa học đảm nhận nhiều bài báo nhất. Ví dụ:
>> ```
5
```
>* $Optimal\text{_}solution$: mảng lưu cách phân công tối ưu. Ví dụ:
>> ```
1 2 4 
1 2 3 
1 2 6 
1 2 4 
3 6 7 
3 5 6 
1 2 6 
4 5 7 
3 4 5 
3 4 5
```
>* $X$: ma trận kích thước $N \times M$, trong đó $X_{ij}= 1$ nếu nhà khoa học $j$ sẽ đảm nhận bài báo $i$, hoặc $X_{ij} = 0$ nếu không đảm nhận. Ví dụ:
>> ```
[[1 1 0 1 0 0 0]
[1 1 1 0 0 0 0]
[1 1 0 0 0 1 0]
[1 1 0 1 0 0 0]
[0 0 1 0 0 1 1]
[0 0 1 0 1 1 0]
[1 1 0 0 0 1 0]
[0 0 1 0 1 0 1]
[0 0 1 1 1 0 0]
[0 0 1 1 1 0 0]
```
>* $workload$: mảng mà ở đó `workload[j]` lưu khối lượng bài báo mà nhà khoa học $j$ đã nhận. Ví dụ: `workload = [5, 5, 5, 5, 4, 4, 2]`

2. **Mô hình hóa**:
> Khi đó, với mỗi một cách phân công, bài báo $i$ sẽ có số giám khảo đảm nhận là $\displaystyle \sum_{j = 1}^{M}{x_{ij}l_{ij}}$. <br>
> Và với mỗi một nhà khoa học $j$, số bài báo người đó đảm nhận sẽ là $\displaystyle \sum_{i = 1}^{N}{x_{ij}l_{ij}}$.
>
> Do đó ta có mô hình:
>> Minimize: $$\displaystyle \max_{j = \overline{1,M}}{\sum_{i = 1}^{N}}{x_{ij}l_{ij}}$$
>> 
>> S.t: $$\displaystyle \sum_{j = 1}^{M}{x_{ij}l_{ij}} \ge K \text{ } \forall i = \overline{1, N}$$

Dễ thấy: nếu tồn tại ít nhất một cách phân công thì cũng tồn tại ít nhất một cách phân công tối ưu. Trong cách phân công tối ưu, tất cả các bài báo đều có **đúng** $K$ nhà khoa học đảm nhận.

> **Chứng minh**: Giả sử có một cách phân công mà ở đó tồn tại ít nhất $1$ bài báo có $K' > K$ nhà khoa học đảm nhận. <br>
Khi đó chọn ngẫu nhiên $1$ nhà khoa học $T$ trong số  $K'$ nhà khoa học đó và loại ông ta ra khỏi việc đảm nhận bài báo này. <br>
Khi đó, $K' - 1 \ge K$ vẫn thỏa mãn yêu cầu "$1$ bài báo có ít nhất $K$ nhà khoa học đảm nhận", trong khi số bài báo nhà khoa học $T$ đảm nhận sẽ ít đi $1$. Nếu nhà khoa học $T$ này lúc đầu là người duy nhất làm nhiều bài báo nhất, thì sau khi loại ông ta ra, ta sẽ được lời giải tối ưu hơn. 

In [17]:
import numpy as np
from ortools.linear_solver import pywraplp
import random as rd
from time import time
import sys

sys.setrecursionlimit(10000000)
FILENAME = "/home/ubuntu/Downloads/data_samples_mini_projects/miniproject-20/data.txt"

## Data generazation

In [18]:
def gen_data(N, M, K):
    infile = open(FILENAME, 'w')

    print(N, M, K, end=' ', file=infile)
    for i in range(N):
        print(file=infile)
        T = rd.randrange(K, M + 1)
        print(T, end=' ', file=infile)
        for j in rd.sample(range(1, M + 1), T):
            print(j, end=' ', file=infile)
    infile.close()

## I/O

In [19]:
def input_from(filename):
    infile = open(filename, 'r')
    
    N, M, K = [int(i) for i in infile.readline().split()]
    
    A = []
    L = np.zeros((N,M), dtype = 'int')
    for i in range(N):
        A.append(sorted([int(k) for k in infile.readline().split()[1:]]))
        if len(A) < K:
            objective_value = "INFEASIBLE"
        for j in A[i]:
            L[i, j - 1] = 1
    infile.close()
    return A, L

def output():
    print(objective_value, end='')
    if objective_value != "INFEASIBLE":
        for i in range(N):
            print()
            for j in range(K):
                print(optimal_solution[i][j], end=' ')

## Different approaches to solve the problem

### OR-tools

#### Source code

In [20]:
def ortools():
    """Minimize the maximal number of articles that a scientist can take on using OR-tools.
    
    solver   solver using Mixed-Integer Programmin with SCIP
    Y        variable mataining the objective function of the SCIP solver    
    """
    global objective_value, optimal_solution
    
    solver = pywraplp.Solver.CreateSolver('SCIP')
    
    INF = solver.infinity()

    X = np.array([[None]*M for i in range(N)])
    Y = solver.IntVar(-INF, INF, 'Y')

    for i in range(N):
        for j in range(M):
            X[i, j] = solver.IntVar(0, int(L[i, j]), 'X[{}, {}]'.format(i, j))

    for i in range(N):
        solver.Add(K == sum(L[i, j]*X[i, j] for j in range(M)))
        
    for j in range(M):
        solver.Add(Y >= sum(L[i, j]*X[i, j] for i in range(N)))

    solver.Minimize(Y)
    status = solver.Solve()
    
    if status == pywraplp.Solver.OPTIMAL:
        objective_value = solver.Objective().Value()
        optimal_solution = [[j + 1 for j in range(M) if X[i, j].solution_value() == 1] for i in range(N)]
    else:
        objective_value = "INFEASIBLE"

### Heuristics

#### Algorithm description

>* Consider the article $i$ that has not been taken by any scientists yet:
>>* Pick out of $A_i$ a list of $K$ scientists who are taking the lightest workload as possible. Assign the article $i$ for them.
>>* Increase the workload of these scientists by $1$.
>* Consider the article $i + 1$.
>* ...

#### Pseudo code

```
Heuristics:    
    if FEASIBLE:
    
        workload[j] <- 0 initialize for each scientist j
        
        for each article i:
        
            list <- sorted( [workload[j], j] for j in A[i] )
            optimal_solution[i] <- list[:K]
            
            for each scientist j in optimal_solution[i]:
                increase workload[j] by 1

        objective_value = max(workload)
```

#### Source code

In [21]:
def heuristics():
    """Minimize the maximal number of articles that a scientist can take on using heuristics.
    
    workload            workload[j] will maintains the number of articles that the scientist j is currently taking
    optimal_solution    optimal_solution[i] maintains the scientists that is currenty taking the article i. After execution, it will be optimal
    """
    global objective_value, optimal_solution
    
    if objective_value != "INFEASIBLE":
        workload = [0]*M                                             # workload a scientist is currently taking, initially 0
        optimal_solution = [[] for i in range(N)]
        for i in range(N):                                           # for each article i
            list = sorted([(workload[j - 1], j) for j in A[i]])      # sort all scientists who CAN take the artcile i in the order of inceasing currently-taking workload
            optimal_solution[i] = [_[1] for _ in list[:K]]           # select in that list K scientists who is currently taking smallest workload
            for j in optimal_solution[i]:                            # then increase the workload of
                workload[j - 1] += 1                                 # each of these scientists by 1

        objective_value = max(workload)

### Heuristics

#### Algorithm description

Claim: In the optimal solution, each article is taken by exactly $K$ scientists.
So we create a 2-dimention array of size $N \times 3$ to save a way of assigning where `solution[i]` is a list of ***indexes*** *of scientist in A[i]*.
Example:
```
A = [[1, 2, 4, 6, 7],        solution = [[1, 2, 3],    ->   optimal_solution = [[1, 2, 4],  workload = [5,
     [1, 2, 3, 4, 5, 7],                 [1, 2, 3],                             [1, 2, 3],              5,
     [1, 2, 6, 7],                       [1, 2, 3],                             [1, 2, 6],              5,
     [1, 2, 4, 5, 7],                    [1, 2, 3],                             [1, 2, 4],              5,
     [1, 2, 3, 6, 7],                    [3, 4, 5],                             [3, 6, 7],              4,
     [1, 3, 4, 5, 6],                    [2, 4, 5],                             [3, 5, 6],              4,
     [1, 2, 6],                          [1, 2, 3],                             [1, 2, 6],              2]
     [2, 4, 5, 7],                       [2, 3, 4],                             [4, 5, 7],
     [1, 3, 4, 5],                       [2, 3, 4],                             [3, 4, 5],
     [1, 2, 3, 4, 5]]                    [3, 4, 5]]                             [3, 4, 5]]
```
With an article `i`:
>* Consider a $K$-subset of $A_i$ corresponding to a way of choosing $K$ scientists who can take on the article $i$. There are totally $C^{K}_{|A[i]|}$ subsets of that way.
>> we assing the article $i$ to these $K$ scientists by saving that subset to `solution[i]`, and simultaneously increase `workload[j]` by $1$.
>>
>> Next, we move to considering the article $i + 1$. <br>
>>> ...
>>>> Ultimately, if the maximum of workload in this way of assignment is less than the smallest `objective_value` that has been recored so far.
>* Roll back to considering another $K$-subset of $A_i$.
>> ...

#### Pseudo code

```
Backtracking:
    initialize workload[j] <- 0 for each scientist j
    
    if the problem is feasible:
        Try(1, 1)     i.e finding the 1st scientist to take the article 1
        
Try(i, t):
    for each scientist j in A[i] that hasn't been assigned i yet:
    
        solution[i][t] <- j            i.e set him as the (t)th scientist who takes the article i
        increase workload[j] by 1
        
        if i = N and t = K:
            then Update
        else if t < K:
            Try(i, t + 1)              i.e find (t + 1)th scientist for the article i
        else if i = N: 
            Try(i + 1, 1)              i.e move to the next article
        
        solution[i][t] <- NULL         i.e omit j in order to try other scientists
        decrease workload[j] by 1
        
Update:
    if max(workload) < objective_value:
        objective_value <- max(workload)
        optimal_solution <- solution
```

In addition, we can apply Branch and bound to discard unnecessary cases: At the beginning of each `for` loop:

```
for each scientist j in A[i] that hasn't been assigned i yet:
       ...
```

we check `workload[j] + 1 < objective_value`. if `True`, we proceed. 

Why? Because `workload[j] + 1 < objective_value` returning `False` means the workload of the scientist `j` after taking on the article `i` will be larger than or equal to the optimal value, so even if we proceed, we will not achieve a better solution for sure.

#### Source code

In [22]:
def backtracking():
    """
    Find the t th scientist for the article i.

    index              the INDEX in A[i] of a scientist
    available_range    the range in which index varies. This ensures eliminating repetition.
    workload           workload[j] will maintains the number of articles that the scientist j is currently taking
    solution           a Nx3 nested list maintaining a way of assignment. Note that ...[i][t] indicates INDEX in A[i], not the name of a scientist.
    """
    solution = [[-1]*K for _ in range(N)]
    workload = [0]*M
    
    def Try(i, t):
        global objective_value
        
        available_range = range(solution[i][t - 1] + 1, len(A[i]) - K + t + 1)
        for index in available_range:
            if workload[A[i][index] - 1] + 1  < objective_value:    # branch and bound
                solution[i][t] = index                              # choose a scientist in A[i]
                workload[A[i][index] - 1] += 1                      # increase the workload of that scientist by 1
                if i == N - 1 and t == K - 1: Update()              # if sufficient scientists are chosen, then Update
                else:
                    if t < K - 1: Try(i, t + 1)                     # find scientists for the article i until enough K are chosen
                    else: Try(i + 1, 0)                             # then move to the next article
                workload[A[i][index] - 1] -= 1                      # After completing Try with that scientist, abandons him
                solution[i][t] = -1                                 # in order to try another candidate

    def Update():
        global objective_value, optimal_solution
        if max(workload) < objective_value:                # if the maximal workload of the current solution is the minimal recorded
            objective_value = max(workload)                # then we will save it
            optimal_solution = [[A[i][j] for j in solution[i]] for i in range(N)]
        
    if objective_value != "INFEASIBLE":
        Try(0, 0)

### Another approach

#### Mô tả thuật toán

#### Mã giả

#### Mã nguồn

Ideal: 
We aim to minimize the_max_the_article_taken_among_scientists
So, I decided to reduce the max of the article till I can’t reduce it any more.
It’s not mean that I can reduce the max to any value arbitrarily
I decided to reduce the max to the predecessor(the number that has the value just only less than the max number. Ex:...)
If after reduction, we can’t not reach the predecessor, so we find the solution…
Else we continue reduce them :)))

Another case: If we don’t have predecessor(ex: a sequence numbers have the same value) 
So, we reduce ‘slowly’: each value reduce only 1
If after reduce, which value doesn’t change is our solution

Cách này thủ công vl nhưng mà nó ra được kết quả tối ưu. Nên tôi nghĩ là từ những constraint tôi đưa #check = False, mọi người có thể dựa vào nó để mà Backtracking
Constrain :
K = the minimum scientist must take a article:
The number of articles can’t not reduce over K
After reduce there are the value can’t not reduce to the predecessor, stable(in case no predecessor) so solution is the max_value_after_reduce

In [23]:
def get_data(filename):
    """
    Process user's input and generate data.
    
    N    number of articles
    M    number of scientists
    K    minimal number of scientists working on each article
    L    matrix representation of data. L[i, j] = 1 means scientist j can take on article i
    """
    infile = open(filename, 'r')
    
    N, M, K = [int(i) for i in infile.readline().split()]
    
    L = np.zeros((N+1,M+1), dtype = 'int')
    # Create N+1 and M+1 so that get the numbers of scientist and article 
    # The additional collumn M+1 and row N+1 give me information of 
    # the number of scientist take an article and the number of article 
    # taken by a scientist in order by get the sum of each collumn and row

    for i in range(1,N+1):
        a = [int(k) for k in infile.readline().split()][1:]
        for j in a:
            L[i,j] = 1
            L[0,j] += L[i,j]
    for j in range(1,M+1):
        for i in range(1,N+1):
            L[i,0] += L[i,j]
    return N, M, K, L

'''
an arrange function that we can 'easily' reduce the number of article
among 'the_scientist_take_the_max_article'
'''     
def arrange(L):
    L = L[L[:,0].argsort()]
    L = L.T
    L = L[L[:,0].argsort()]
    L = L.T
    return L
def predecessor(L):
    #find the predecessor of max(article taken by the scientist)
    i = 0
    while max(L) - L[len(L)-1-i] == 0 and i != len(L) :
        i += 1
    return [L[len(L)-1-i],i]

'''
    Stop condition for this algorithm:
    - if all the number of scientists take an article = K(the minimum scientist need to take each article)
    - if we can't reduce the_max_number of article taken by a scientist
    any more OR the_max_number after reduce is not equal to the
    predecessor(of max).
    #Note
        #trong qua trinh tru thi se co hang bang K.
        #nhung nhung hang o duoi thi co hang > K
        #tao dieu kien dung(tai mot hang) khi ma ta
        #tru den gia tri toi thieu(o day la K) 
        => stopCDT()
'''
def stopCDT(L,K):
    address = np.where(L[:,0][1:] == K)[0]
    if address.size > 0:
        return max(address)
    else:
        return 0
def solver(L,N,M,K):
    L = arrange(L)
    global check
    p = predecessor(L[0][1:])
    t = 0  
    i = 0
    t1 = float('inf')
    st = stopCDT(L, K) 
    if L[N,0] == K:
        check = False    
    else:
        if p[0] != max(L[0]): #this sequence has predecessor
            for j in range(p[1]): #interate till find the predecessor
                while (L[0,M-j] != p[0]): #check when to stop reduce
                    if N-i == st:
                        break    
                    if (L[N-i,0]!= K) :    
                        if L[N-i,M-j] == 1:   
                            L[N-i,M-j] = 0
                            L[0,M-j] -= 1
                            L[N-i,0] -= 1
                            t += 1  #check if we can reduce the_max_article_taken by a scientist 
                                    #equal to predecessor
                                    #if not, break and then solution = max(after reduce)
                            if st != 0 and st != N:#update stop
                                k = st 
                                while (L[k,0] == K) and k!=N: 
                                    k+=1
                                st = k                            
                    i += 1
                if t1 > t:
                    t1 = t
                i = 0
                t = 0
            if t1 == 0:
                check = False
            elif (t1 < max(L[0]) - predecessor(L[0])[0]):
                return L
                check = False
        else:   # this sequence has no predecessor
            for j in range(p[1]):
                while N-i != st:
                    if L[N-i,0] != K:
                        if L[N-i,M-j] == 1:   
                            L[N-i,M-j] = 0
                            L[0,M-j] -= 1
                            L[N-i,0] -= 1
                            t += 1
                            if st != 0 and st != N:#update stop
                                k = st 
                                while (L[k,0] == K) and k!=N: 
                                    k+=1
                                st = k   
                        break
                    i += 1
                if t1 > t:
                    t1 = t
                t = 0
                i = 0
            if t1 == 0:
                return L
                check = False
    return L
def printmt(L,N,M):
    a = []
    for i in range(1,N+1):
        for j in range(1,M+1):
            if L[i,j] != 0:
                a.append(j)
        print(a)
        a = []

check = True
def main():
    N, M, K, L = get_data(FILENAME)
    start_time = time()
    while check:
        L = solver(L,N,M,K)
    end_time = time()
    print(end_time - start_time)
    #print(L)
    #printmt(L,N,M)
    #print('solution is: ', max(L[0]))
# main()

## Chạy chương trình

In [ ]:
data_sizes = [(10, 7, 3), (50, 35, 15), (100, 70, 30), (500, 350, 150), (1000, 700, 300)]

for (N, M, K) in data_sizes:
    gen_data(N, M, K)

    start_time = time()

    A, L = input_from(FILENAME)
    objective_value, optimal_solution = float('inf'), []
    backtracking()

    end_time = time()
    print(end_time - start_time)

    output()

#### Thời gian chạy và Độ phức tạp


Data|Size|MIP|Heuristics|Backtracking|4th approach
:--|--:|--:|--:|--:|--:
Complexity||Unknown|$O(N\cdot M \log{M})$|
Data 1|10||0.00012
Data 2|50||0.00073
Data 3|100||0.01220
Data 4|500||0.06282
Data 5|1000||0.26164